### ISSUE TITLE
Get  EXC_BAD_ACCESS (code=1, address=0x8) when try to build

### ISSUE THREAD

**Issue by unbrokendub** [emreyolcu/drag-scroll#1]
Hello. Did you still maintain this app?

Debugger show me that error happens on this line:
runLoopSource = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, eventTap, 0);

Looks like it wants Accesebilty, but i enabled PixelScroll in system setting already.

Platform: MacOS Sonoma, Apple Silicon, xCode 15.2

**Comment by emreyolcu** [comment]
Sorry for the late response. I have added some instructions to the README to help with such issues. If they do not solve your problem, unfortunately I will not be able to help, because I am using an older macOS version and cannot reproduce the problem.
