### ISSUE TITLE
Feature Suggestion: Invert scrolling

### ISSUE THREAD

**Issue by thebigluke** [emreyolcu/drag-scroll#6]
Hi, would be nice to have the option of 'natural scrolling', basically inverted, so it acts like a phone/tablet.

**Comment by emreyolcu** [comment]
You can achieve this by setting a negative speed. Please see the [configuration section](https://github.com/emreyolcu/drag-scroll?tab=readme-ov-file#configuration) of the README.

**Comment by thebigluke** [comment]
Yes I already tried that but it didn't work.

I should say that I'm using a Wacom pen and tablet, I wanted to use the middle button but that didn't work either, so it only works when the pen is hovering above the tablet with the modifier (shift) key pressed.
It's working for me like that though, I just wanted to invert the scrolling.

**Comment by emreyolcu** [comment]
Did you restart the application after setting speed to a negative value? Also, could you share the output of `defaults read com.emreyolcu.DragScroll`?

**Comment by thebigluke** [comment]
All good!
I didn't realise I had to kill and then restart the app for the settings to take hold...
Thank you, fastest feature update after a request ever!

{
    button = 5;
    speed = "-1";
}
